use crate::models::entities::lol_match_timeline::ItemEvent;
use serde::{Deserialize, Serialize};


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LolSummonerChampionPage{
    pub champion_id: i32,
    pub total_matches: i64,
    pub total_wins: i64,
    pub total_lose: i64,
    pub win_rate: f64,
    pub avg_kda: f64,
    pub avg_kill_participation: f64,
    pub avg_kills: f64,
    pub avg_deaths: f64,
    pub avg_assists: f64,
    pub avg_gold_earned: f64,
    pub avg_cs: f64,
    pub avg_damage_dealt_to_champions: f64,
    pub avg_damage_taken: f64,
    pub total_double_kills: i64,
    pub total_triple_kills: i64,
    pub total_quadra_kills: i64,
    pub total_penta_kills: i64,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LolMatchDefaultParticipantMatchesPage {
    pub summoner_id: i32,
    pub match_id: i32,
    pub riot_match_id: String,
    pub match_ended_since: String,
    pub match_duration: String,
    pub queue: String,
    pub platform: String,
    pub champion_id: i32,
    pub won: bool,
    pub champ_level: i32,
    pub kda: f64,
    pub kill_participation: f64,
    pub kills: i32,
    pub deaths: i32,
    pub assists: i32,
    pub summoner_spell1_id: i32,
    pub summoner_spell2_id: i32,
    pub perk_primary_selection_id: i32,
    pub perk_sub_style_id: i32,
    pub item0_id: i32,
    pub item1_id: i32,
    pub item2_id: i32,
    pub item3_id: i32,
    pub item4_id: i32,
    pub item5_id: i32,
    pub item6_id: i32,

    pub participants: Vec<LolMatchParticipantMatchesPage>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LolMatchParticipantMatchesPage {
    pub lol_match_id: i32,
    pub summoner_id: i32,
    pub summoner_name: String,
    pub summoner_tag_line: String,
    pub summoner_platform: String,
    pub champion_id: i32,
    pub team_id: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LolMatchParticipantMatchesDetailPage {
    pub id: i32,
    pub lol_match_id: i32,
    pub summoner_id: i32,
    pub summoner_name: String,
    pub summoner_tag_line: String,
    pub summoner_platform: String,
    pub summoner_icon_id: i32,
    pub summoner_level: i64,
    pub champion_id: i32,
    pub team_id: i32,
    pub won: bool,
    pub kills: i32,
    pub deaths: i32,
    pub assists: i32,
    pub champ_level: i32,
    pub kda: f64,
    pub kill_participation: f64,
    pub damage_dealt_to_champions: i32,
    pub damage_taken: i32,
    pub gold_earned: i32,
    pub wards_placed: i32,
    pub cs: i32,
    pub summoner_spell1_id: i32,
    pub summoner_spell2_id: i32,
    pub perk_defense_id: i32,
    pub perk_flex_id: i32,
    pub perk_offense_id: i32,
    pub perk_primary_style_id: i32,
    pub perk_sub_style_id: i32,
    pub perk_primary_selection_id: i32,
    pub perk_primary_selection1_id: i32,
    pub perk_primary_selection2_id: i32,
    pub perk_primary_selection3_id: i32,
    pub perk_sub_selection1_id: i32,
    pub perk_sub_selection2_id: i32,
    pub item0_id: i32,
    pub item1_id: i32,
    pub item2_id: i32,
    pub item3_id: i32,
    pub item4_id: i32,
    pub item5_id: i32,
    pub item6_id: i32,
    pub items_event_timeline: Vec<(i32, Vec<ItemEvent>)>,
    pub skills_timeline: Vec<i32>,
}


/// Represents a participant in a League of Legends match.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LolMatchParticipant {
    pub id: i32,
    pub champion_id: i32,
    pub summoner_id: i32,
    pub lol_match_id: i32,
    pub summoner_spell1_id: i32,
    pub summoner_spell2_id: i32,
    pub team_id: i32,
    pub won: bool,
    pub kda: f64,
    pub kill_participation: f64,
    pub kills: i32,
    pub deaths: i32,
    pub assists: i32,
    pub champ_level: i32,
    pub damage_dealt_to_champions: i32,
    pub damage_taken: i32,
    pub gold_earned: i32,
    pub wards_placed: i32,
    pub cs: i32,
    pub cs_per_minute: f64,
    pub double_kills: i32,
    pub triple_kills: i32,
    pub quadra_kills: i32,
    pub penta_kills: i32,
    pub perk_defense_id: i32,
    pub perk_flex_id: i32,
    pub perk_offense_id: i32,
    pub perk_primary_style_id: i32,
    pub perk_sub_style_id: i32,
    pub perk_primary_selection_id: i32,
    pub perk_primary_selection1_id: i32,
    pub perk_primary_selection2_id: i32,
    pub perk_primary_selection3_id: i32,
    pub perk_sub_selection1_id: i32,
    pub perk_sub_selection2_id: i32,
    pub item0_id: i32,
    pub item1_id: i32,
    pub item2_id: i32,
    pub item3_id: i32,
    pub item4_id: i32,
    pub item5_id: i32,
    pub item6_id: i32,
}



