#[repr(u16)]
#[derive(
    Debug,
    Clone,
    Copy,
    Eq,
    PartialEq,
    Hash,
)]
pub enum Champion {
    UNKNOWN = 0,
    Aatrox = 266,
    Ahri = 103,
    Akali = 84,
    Akshan = 166,
    Alistar = 12,
    Ambessa = 799,
    Amumu = 32,
    Anivia = 34,
    Annie = 1,
    Aphelios = 523,
    Ashe = 22,
    AurelionSol = 136,
    Aurora = 893,
    Azir = 268,
    Bard = 432,
    BelVeth = 200,
    Blitzcrank = 53,
    Brand = 63,
    Braum = 201,
    Briar = 233,
    Caitlyn = 51,
    Camille = 164,
    Cassiopeia = 69,
    ChoGath = 31,
    Corki = 42,
    Darius = 122,
    Diana = 131,
    DrMundo = 36,
    Draven = 119,
    Ekko = 245,
    Elise = 60,
    Evelynn = 28,
    Ezreal = 81,
    Fiddlesticks = 9,
    Fiora = 114,
    Fizz = 105,
    Galio = 3,
    Gangplank = 41,
    Garen = 86,
    Gnar = 150,
    Gragas = 79,
    Graves = 104,
    Gwen = 887,
    Hecarim = 120,
    Heimerdinger = 74,
    Hwei = 910,
    Illaoi = 420,
    Irelia = 39,
    Ivern = 427,
    Janna = 40,
    JarvanIV = 59,
    Jax = 24,
    Jayce = 126,
    Jhin = 202,
    Jinx = 222,
    KSante = 897,
    KaiSa = 145,
    Kalista = 429,
    Karma = 43,
    Karthus = 30,
    Kassadin = 38,
    Katarina = 55,
    Kayle = 10,
    Kayn = 141,
    Kennen = 85,
    KhaZix = 121,
    Kindred = 203,
    Kled = 240,
    KogMaw = 96,
    LeBlanc = 7,
    LeeSin = 64,
    Leona = 89,
    Lillia = 876,
    Lissandra = 127,
    Lucian = 236,
    Lulu = 117,
    Lux = 99,
    Malphite = 54,
    Malzahar = 90,
    Maokai = 57,
    MasterYi = 11,
    Milio = 902,
    MissFortune = 21,
    Mordekaiser = 82,
    Morgana = 25,
    NAAFIRI = 950,
    Nami = 267,
    Nasus = 75,
    Nautilus = 111,
    Neeko = 518,
    Nidalee = 76,
    Nilah = 895,
    Nocturne = 56,
    NunuWillump = 20,
    Olaf = 2,
    Orianna = 61,
    Ornn = 516,
    Pantheon = 80,
    Poppy = 78,
    Pyke = 555,
    Qiyana = 246,
    Quinn = 133,
    Rakan = 497,
    Rammus = 33,
    RekSai = 421,
    Rell = 526,
    RenataGlasc = 888,
    Renekton = 58,
    Rengar = 107,
    Riven = 92,
    Rumble = 68,
    Ryze = 13,
    Samira = 360,
    Sejuani = 113,
    Senna = 235,
    Seraphine = 147,
    Sett = 875,
    Shaco = 35,
    Shen = 98,
    Shyvana = 102,
    Singed = 27,
    Sion = 14,
    Sivir = 15,
    Skarner = 72,
    Smolder = 901,
    Sona = 37,
    Soraka = 16,
    Swain = 50,
    Sylas = 517,
    Syndra = 134,
    TahmKench = 223,
    Taliyah = 163,
    Talon = 91,
    Taric = 44,
    Teemo = 17,
    Thresh = 412,
    Tristana = 18,
    Trundle = 48,
    Tryndamere = 23,
    TwistedFate = 4,
    Twitch = 29,
    Udyr = 77,
    Urgot = 6,
    Varus = 110,
    Vayne = 67,
    Veigar = 45,
    VelKoz = 161,
    Vex = 711,
    Vi = 254,
    Viego = 234,
    Viktor = 112,
    Vladimir = 8,
    Volibear = 106,
    Warwick = 19,
    Wukong = 62,
    Xayah = 498,
    Xerath = 101,
    XinZhao = 5,
    Yasuo = 157,
    Yone = 777,
    Yorick = 83,
    Yuumi = 350,
    Zac = 154,
    Zed = 238,
    Zeri = 221,
    Ziggs = 115,
    Zilean = 26,
    Zoe = 142,
    Zyra = 143,
}


impl Champion {
    pub const fn to_str(&self) -> &'static str {
        match self {
            Champion::Aatrox => "Aatrox",
            Champion::Ahri => "Ahri",
            Champion::Akali => "Akali",
            Champion::Akshan => "Akshan",
            Champion::Alistar => "Alistar",
            Champion::Ambessa => "Ambessa",
            Champion::Amumu => "Amumu",
            Champion::Anivia => "Anivia",
            Champion::Annie => "Annie",
            Champion::Aphelios => "Aphelios",
            Champion::Ashe => "Ashe",
            Champion::AurelionSol => "AurelionSol",
            Champion::Aurora => "Aurora",
            Champion::Azir => "Azir",
            Champion::Bard => "Bard",
            Champion::BelVeth => "BelVeth",
            Champion::Blitzcrank => "Blitzcrank",
            Champion::Brand => "Brand",
            Champion::Braum => "Braum",
            Champion::Briar => "Briar",
            Champion::Caitlyn => "Caitlyn",
            Champion::Camille => "Camille",
            Champion::Cassiopeia => "Cassiopeia",
            Champion::ChoGath => "ChoGath",
            Champion::Corki => "Corki",
            Champion::Darius => "Darius",
            Champion::Diana => "Diana",
            Champion::DrMundo => "DrMundo",
            Champion::Draven => "Draven",
            Champion::Ekko => "Ekko",
            Champion::Elise => "Elise",
            Champion::Evelynn => "Evelynn",
            Champion::Ezreal => "Ezreal",
            Champion::Fiddlesticks => "Fiddlesticks",
            Champion::Fiora => "Fiora",
            Champion::Fizz => "Fizz",
            Champion::Galio => "Galio",
            Champion::Gangplank => "Gangplank",
            Champion::Garen => "Garen",
            Champion::Gnar => "Gnar",
            Champion::Gragas => "Gragas",
            Champion::Graves => "Graves",
            Champion::Gwen => "Gwen",
            Champion::Hecarim => "Hecarim",
            Champion::Heimerdinger => "Heimerdinger",
            Champion::Hwei => "Hwei",
            Champion::Illaoi => "Illaoi",
            Champion::Irelia => "Irelia",
            Champion::Ivern => "Ivern",
            Champion::Janna => "Janna",
            Champion::JarvanIV => "JarvanIV",
            Champion::Jax => "Jax",
            Champion::Jayce => "Jayce",
            Champion::Jhin => "Jhin",
            Champion::Jinx => "Jinx",
            Champion::KSante => "KSante",
            Champion::KaiSa => "KaiSa",
            Champion::Kalista => "Kalista",
            Champion::Karma => "Karma",
            Champion::Karthus => "Karthus",
            Champion::Kassadin => "Kassadin",
            Champion::Katarina => "Katarina",
            Champion::Kayle => "Kayle",
            Champion::Kayn => "Kayn",
            Champion::Kennen => "Kennen",
            Champion::KhaZix => "KhaZix",
            Champion::Kindred => "Kindred",
            Champion::Kled => "Kled",
            Champion::KogMaw => "KogMaw",
            Champion::LeBlanc => "LeBlanc",
            Champion::LeeSin => "LeeSin",
            Champion::Leona => "Leona",
            Champion::Lillia => "Lillia",
            Champion::Lissandra => "Lissandra",
            Champion::Lucian => "Lucian",
            Champion::Lulu => "Lulu",
            Champion::Lux => "Lux",
            Champion::Malphite => "Malphite",
            Champion::Malzahar => "Malzahar",
            Champion::Maokai => "Maokai",
            Champion::MasterYi => "MasterYi",
            Champion::Milio => "Milio",
            Champion::MissFortune => "MissFortune",
            Champion::Mordekaiser => "Mordekaiser",
            Champion::Morgana => "Morgana",
            Champion::NAAFIRI => "NAAFIRI",
            Champion::Nami => "Nami",
            Champion::Nasus => "Nasus",
            Champion::Nautilus => "Nautilus",
            Champion::Neeko => "Neeko",
            Champion::Nidalee => "Nidalee",
            Champion::Nilah => "Nilah",
            Champion::Nocturne => "Nocturne",
            Champion::NunuWillump => "NunuWillump",
            Champion::Olaf => "Olaf",
            Champion::Orianna => "Orianna",
            Champion::Ornn => "Ornn",
            Champion::Pantheon => "Pantheon",
            Champion::Poppy => "Poppy",
            Champion::Pyke => "Pyke",
            Champion::Qiyana => "Qiyana",
            Champion::Quinn => "Quinn",
            Champion::Rakan => "Rakan",
            Champion::Rammus => "Rammus",
            Champion::RekSai => "RekSai",
            Champion::Rell => "Rell",
            Champion::RenataGlasc => "RenataGlasc",
            Champion::Renekton => "Renekton",
            Champion::Rengar => "Rengar",
            Champion::Riven => "Riven",
            Champion::Rumble => "Rumble",
            Champion::Ryze => "Ryze",
            Champion::Samira => "Samira",
            Champion::Sejuani => "Sejuani",
            Champion::Senna => "Senna",
            Champion::Seraphine => "Seraphine",
            Champion::Sett => "Sett",
            Champion::Shaco => "Shaco",
            Champion::Shen => "Shen",
            Champion::Shyvana => "Shyvana",
            Champion::Singed => "Singed",
            Champion::Sion => "Sion",
            Champion::Sivir => "Sivir",
            Champion::Skarner => "Skarner",
            Champion::Smolder => "Smolder",
            Champion::Sona => "Sona",
            Champion::Soraka => "Soraka",
            Champion::Swain => "Swain",
            Champion::Sylas => "Sylas",
            Champion::Syndra => "Syndra",
            Champion::TahmKench => "TahmKench",
            Champion::Taliyah => "Taliyah",
            Champion::Talon => "Talon",
            Champion::Taric => "Taric",
            Champion::Teemo => "Teemo",
            Champion::Thresh => "Thresh",
            Champion::Tristana => "Tristana",
            Champion::Trundle => "Trundle",
            Champion::Tryndamere => "Tryndamere",
            Champion::TwistedFate => "TwistedFate",
            Champion::Twitch => "Twitch",
            Champion::Udyr => "Udyr",
            Champion::Urgot => "Urgot",
            Champion::Varus => "Varus",
            Champion::Vayne => "Vayne",
            Champion::Veigar => "Veigar",
            Champion::VelKoz => "VelKoz",
            Champion::Vex => "Vex",
            Champion::Vi => "Vi",
            Champion::Viego => "Viego",
            Champion::Viktor => "Viktor",
            Champion::Vladimir => "Vladimir",
            Champion::Volibear => "Volibear",
            Champion::Warwick => "Warwick",
            Champion::Wukong => "Wukong",
            Champion::Xayah => "Xayah",
            Champion::Xerath => "Xerath",
            Champion::XinZhao => "XinZhao",
            Champion::Yasuo => "Yasuo",
            Champion::Yone => "Yone",
            Champion::Yorick => "Yorick",
            Champion::Yuumi => "Yuumi",
            Champion::Zac => "Zac",
            Champion::Zed => "Zed",
            Champion::Zeri => "Zeri",
            Champion::Ziggs => "Ziggs",
            Champion::Zilean => "Zilean",
            Champion::Zoe => "Zoe",
            Champion::Zyra => "Zyra",
            Champion::UNKNOWN => "UNKNOWN",
        }
    }
}


impl From<u16> for Champion {
    fn from(value: u16) -> Self {
        match value {
            266 => Champion::Aatrox,
            103 => Champion::Ahri,
            84 => Champion::Akali,
            166 => Champion::Akshan,
            12 => Champion::Alistar,
            799 => Champion::Ambessa,
            32 => Champion::Amumu,
            34 => Champion::Anivia,
            1 => Champion::Annie,
            523 => Champion::Aphelios,
            22 => Champion::Ashe,
            136 => Champion::AurelionSol,
            893 => Champion::Aurora,
            268 => Champion::Azir,
            432 => Champion::Bard,
            200 => Champion::BelVeth,
            53 => Champion::Blitzcrank,
            63 => Champion::Brand,
            201 => Champion::Braum,
            233 => Champion::Briar,
            51 => Champion::Caitlyn,
            164 => Champion::Camille,
            69 => Champion::Cassiopeia,
            31 => Champion::ChoGath,
            42 => Champion::Corki,
            122 => Champion::Darius,
            131 => Champion::Diana,
            36 => Champion::DrMundo,
            119 => Champion::Draven,
            245 => Champion::Ekko,
            60 => Champion::Elise,
            28 => Champion::Evelynn,
            81 => Champion::Ezreal,
            9 => Champion::Fiddlesticks,
            114 => Champion::Fiora,
            105 => Champion::Fizz,
            3 => Champion::Galio,
            41 => Champion::Gangplank,
            86 => Champion::Garen,
            150 => Champion::Gnar,
            79 => Champion::Gragas,
            104 => Champion::Graves,
            887 => Champion::Gwen,
            120 => Champion::Hecarim,
            74 => Champion::Heimerdinger,
            910 => Champion::Hwei,
            420 => Champion::Illaoi,
            39 => Champion::Irelia,
            427 => Champion::Ivern,
            40 => Champion::Janna,
            59 => Champion::JarvanIV,
            24 => Champion::Jax,
            126 => Champion::Jayce,
            202 => Champion::Jhin,
            222 => Champion::Jinx,
            897 => Champion::KSante,
            145 => Champion::KaiSa,
            429 => Champion::Kalista,
            43 => Champion::Karma,
            30 => Champion::Karthus,
            38 => Champion::Kassadin,
            55 => Champion::Katarina,
            10 => Champion::Kayle,
            141 => Champion::Kayn,
            85 => Champion::Kennen,
            121 => Champion::KhaZix,
            203 => Champion::Kindred,
            240 => Champion::Kled,
            96 => Champion::KogMaw,
            7 => Champion::LeBlanc,
            64 => Champion::LeeSin,
            89 => Champion::Leona,
            876 => Champion::Lillia,
            127 => Champion::Lissandra,
            236 => Champion::Lucian,
            117 => Champion::Lulu,
            99 => Champion::Lux,
            54 => Champion::Malphite,
            90 => Champion::Malzahar,
            57 => Champion::Maokai,
            11 => Champion::MasterYi,
            902 => Champion::Milio,
            21 => Champion::MissFortune,
            82 => Champion::Mordekaiser,
            25 => Champion::Morgana,
            950 => Champion::NAAFIRI,
            267 => Champion::Nami,
            75 => Champion::Nasus,
            111 => Champion::Nautilus,
            518 => Champion::Neeko,
            76 => Champion::Nidalee,
            895 => Champion::Nilah,
            56 => Champion::Nocturne,
            20 => Champion::NunuWillump,
            2 => Champion::Olaf,
            61 => Champion::Orianna,
            516 => Champion::Ornn,
            80 => Champion::Pantheon,
            78 => Champion::Poppy,
            555 => Champion::Pyke,
            246 => Champion::Qiyana,
            133 => Champion::Quinn,
            497 => Champion::Rakan,
            33 => Champion::Rammus,
            421 => Champion::RekSai,
            526 => Champion::Rell,
            888 => Champion::RenataGlasc,
            58 => Champion::Renekton,
            107 => Champion::Rengar,
            92 => Champion::Riven,
            68 => Champion::Rumble,
            13 => Champion::Ryze,
            360 => Champion::Samira,
            113 => Champion::Sejuani,
            235 => Champion::Senna,
            147 => Champion::Seraphine,
            875 => Champion::Sett,
            35 => Champion::Shaco,
            98 => Champion::Shen,
            102 => Champion::Shyvana,
            27 => Champion::Singed,
            14 => Champion::Sion,
            15 => Champion::Sivir,
            72 => Champion::Skarner,
            901 => Champion::Smolder,
            37 => Champion::Sona,
            16 => Champion::Soraka,
            50 => Champion::Swain,
            517 => Champion::Sylas,
            134 => Champion::Syndra,
            223 => Champion::TahmKench,
            163 => Champion::Taliyah,
            91 => Champion::Talon,
            44 => Champion::Taric,
            17 => Champion::Teemo,
            412 => Champion::Thresh,
            18 => Champion::Tristana,
            48 => Champion::Trundle,
            23 => Champion::Tryndamere,
            4 => Champion::TwistedFate,
            29 => Champion::Twitch,
            77 => Champion::Udyr,
            6 => Champion::Urgot,
            110 => Champion::Varus,
            67 => Champion::Vayne,
            45 => Champion::Veigar,
            161 => Champion::VelKoz,
            711 => Champion::Vex,
            254 => Champion::Vi,
            234 => Champion::Viego,
            112 => Champion::Viktor,
            8 => Champion::Vladimir,
            106 => Champion::Volibear,
            19 => Champion::Warwick,
            62 => Champion::Wukong,
            498 => Champion::Xayah,
            101 => Champion::Xerath,
            5 => Champion::XinZhao,
            157 => Champion::Yasuo,
            777 => Champion::Yone,
            83 => Champion::Yorick,
            350 => Champion::Yuumi,
            154 => Champion::Zac,
            238 => Champion::Zed,
            221 => Champion::Zeri,
            115 => Champion::Ziggs,
            26 => Champion::Zilean,
            142 => Champion::Zoe,
            143 => Champion::Zyra,
            _ => Champion::UNKNOWN,
        }
    }
}


pub static CHAMPION_OPTIONS: &[(u16, &str)] = &[
    (Champion::Aatrox as u16, Champion::Aatrox.to_str()),
    (Champion::Ahri as u16, Champion::Ahri.to_str()),
    (Champion::Akali as u16, Champion::Akali.to_str()),
    (Champion::Akshan as u16, Champion::Akshan.to_str()),
    (Champion::Alistar as u16, Champion::Alistar.to_str()),
    (Champion::Ambessa as u16, Champion::Ambessa.to_str()),
    (Champion::Amumu as u16, Champion::Amumu.to_str()),
    (Champion::Anivia as u16, Champion::Anivia.to_str()),
    (Champion::Annie as u16, Champion::Annie.to_str()),
    (Champion::Aphelios as u16, Champion::Aphelios.to_str()),
    (Champion::Ashe as u16, Champion::Ashe.to_str()),
    (Champion::AurelionSol as u16, Champion::AurelionSol.to_str()),
    (Champion::Aurora as u16, Champion::Aurora.to_str()),
    (Champion::Azir as u16, Champion::Azir.to_str()),
    (Champion::Bard as u16, Champion::Bard.to_str()),
    (Champion::BelVeth as u16, Champion::BelVeth.to_str()),
    (Champion::Blitzcrank as u16, Champion::Blitzcrank.to_str()),
    (Champion::Brand as u16, Champion::Brand.to_str()),
    (Champion::Braum as u16, Champion::Braum.to_str()),
    (Champion::Briar as u16, Champion::Briar.to_str()),
    (Champion::Caitlyn as u16, Champion::Caitlyn.to_str()),
    (Champion::Camille as u16, Champion::Camille.to_str()),
    (Champion::Cassiopeia as u16, Champion::Cassiopeia.to_str()),
    (Champion::ChoGath as u16, Champion::ChoGath.to_str()),
    (Champion::Corki as u16, Champion::Corki.to_str()),
    (Champion::Darius as u16, Champion::Darius.to_str()),
    (Champion::Diana as u16, Champion::Diana.to_str()),
    (Champion::DrMundo as u16, Champion::DrMundo.to_str()),
    (Champion::Draven as u16, Champion::Draven.to_str()),
    (Champion::Ekko as u16, Champion::Ekko.to_str()),
    (Champion::Elise as u16, Champion::Elise.to_str()),
    (Champion::Evelynn as u16, Champion::Evelynn.to_str()),
    (Champion::Ezreal as u16, Champion::Ezreal.to_str()),
    (Champion::Fiddlesticks as u16, Champion::Fiddlesticks.to_str()),
    (Champion::Fiora as u16, Champion::Fiora.to_str()),
    (Champion::Fizz as u16, Champion::Fizz.to_str()),
    (Champion::Galio as u16, Champion::Galio.to_str()),
    (Champion::Gangplank as u16, Champion::Gangplank.to_str()),
    (Champion::Garen as u16, Champion::Garen.to_str()),
    (Champion::Gnar as u16, Champion::Gnar.to_str()),
    (Champion::Gragas as u16, Champion::Gragas.to_str()),
    (Champion::Graves as u16, Champion::Graves.to_str()),
    (Champion::Gwen as u16, Champion::Gwen.to_str()),
    (Champion::Hecarim as u16, Champion::Hecarim.to_str()),
    (Champion::Heimerdinger as u16, Champion::Heimerdinger.to_str()),
    (Champion::Hwei as u16, Champion::Hwei.to_str()),
    (Champion::Illaoi as u16, Champion::Illaoi.to_str()),
    (Champion::Irelia as u16, Champion::Irelia.to_str()),
    (Champion::Ivern as u16, Champion::Ivern.to_str()),
    (Champion::Janna as u16, Champion::Janna.to_str()),
    (Champion::JarvanIV as u16, Champion::JarvanIV.to_str()),
    (Champion::Jax as u16, Champion::Jax.to_str()),
    (Champion::Jayce as u16, Champion::Jayce.to_str()),
    (Champion::Jhin as u16, Champion::Jhin.to_str()),
    (Champion::Jinx as u16, Champion::Jinx.to_str()),
    (Champion::KSante as u16, Champion::KSante.to_str()),
    (Champion::KaiSa as u16, Champion::KaiSa.to_str()),
    (Champion::Kalista as u16, Champion::Kalista.to_str()),
    (Champion::Karma as u16, Champion::Karma.to_str()),
    (Champion::Karthus as u16, Champion::Karthus.to_str()),
    (Champion::Kassadin as u16, Champion::Kassadin.to_str()),
    (Champion::Katarina as u16, Champion::Katarina.to_str()),
    (Champion::Kayle as u16, Champion::Kayle.to_str()),
    (Champion::Kayn as u16, Champion::Kayn.to_str()),
    (Champion::Kennen as u16, Champion::Kennen.to_str()),
    (Champion::KhaZix as u16, Champion::KhaZix.to_str()),
    (Champion::Kindred as u16, Champion::Kindred.to_str()),
    (Champion::Kled as u16, Champion::Kled.to_str()),
    (Champion::KogMaw as u16, Champion::KogMaw.to_str()),
    (Champion::LeBlanc as u16, Champion::LeBlanc.to_str()),
    (Champion::LeeSin as u16, Champion::LeeSin.to_str()),
    (Champion::Leona as u16, Champion::Leona.to_str()),
    (Champion::Lillia as u16, Champion::Lillia.to_str()),
    (Champion::Lissandra as u16, Champion::Lissandra.to_str()),
    (Champion::Lucian as u16, Champion::Lucian.to_str()),
    (Champion::Lulu as u16, Champion::Lulu.to_str()),
    (Champion::Lux as u16, Champion::Lux.to_str()),
    (Champion::Malphite as u16, Champion::Malphite.to_str()),
    (Champion::Malzahar as u16, Champion::Malzahar.to_str()),
    (Champion::Maokai as u16, Champion::Maokai.to_str()),
    (Champion::MasterYi as u16, Champion::MasterYi.to_str()),
    (Champion::Milio as u16, Champion::Milio.to_str()),
    (Champion::MissFortune as u16, Champion::MissFortune.to_str()),
    (Champion::Mordekaiser as u16, Champion::Mordekaiser.to_str()),
    (Champion::Morgana as u16, Champion::Morgana.to_str()),
    (Champion::NAAFIRI as u16, Champion::NAAFIRI.to_str()),
    (Champion::Nami as u16, Champion::Nami.to_str()),
    (Champion::Nasus as u16, Champion::Nasus.to_str()),
    (Champion::Nautilus as u16, Champion::Nautilus.to_str()),
    (Champion::Neeko as u16, Champion::Neeko.to_str()),
    (Champion::Nidalee as u16, Champion::Nidalee.to_str()),
    (Champion::Nilah as u16, Champion::Nilah.to_str()),
    (Champion::Nocturne as u16, Champion::Nocturne.to_str()),
    (Champion::NunuWillump as u16, Champion::NunuWillump.to_str()),
    (Champion::Olaf as u16, Champion::Olaf.to_str()),
    (Champion::Orianna as u16, Champion::Orianna.to_str()),
    (Champion::Ornn as u16, Champion::Ornn.to_str()),
    (Champion::Pantheon as u16, Champion::Pantheon.to_str()),
    (Champion::Poppy as u16, Champion::Poppy.to_str()),
    (Champion::Pyke as u16, Champion::Pyke.to_str()),
    (Champion::Qiyana as u16, Champion::Qiyana.to_str()),
    (Champion::Quinn as u16, Champion::Quinn.to_str()),
    (Champion::Rakan as u16, Champion::Rakan.to_str()),
    (Champion::Rammus as u16, Champion::Rammus.to_str()),
    (Champion::RekSai as u16, Champion::RekSai.to_str()),
    (Champion::Rell as u16, Champion::Rell.to_str()),
    (Champion::RenataGlasc as u16, Champion::RenataGlasc.to_str()),
    (Champion::Renekton as u16, Champion::Renekton.to_str()),
    (Champion::Rengar as u16, Champion::Rengar.to_str()),
    (Champion::Riven as u16, Champion::Riven.to_str()),
    (Champion::Rumble as u16, Champion::Rumble.to_str()),
    (Champion::Ryze as u16, Champion::Ryze.to_str()),
    (Champion::Samira as u16, Champion::Samira.to_str()),
    (Champion::Sejuani as u16, Champion::Sejuani.to_str()),
    (Champion::Senna as u16, Champion::Senna.to_str()),
    (Champion::Seraphine as u16, Champion::Seraphine.to_str()),
    (Champion::Sett as u16, Champion::Sett.to_str()),
    (Champion::Shaco as u16, Champion::Shaco.to_str()),
    (Champion::Shen as u16, Champion::Shen.to_str()),
    (Champion::Shyvana as u16, Champion::Shyvana.to_str()),
    (Champion::Singed as u16, Champion::Singed.to_str()),
    (Champion::Sion as u16, Champion::Sion.to_str()),
    (Champion::Sivir as u16, Champion::Sivir.to_str()),
    (Champion::Skarner as u16, Champion::Skarner.to_str()),
    (Champion::Smolder as u16, Champion::Smolder.to_str()),
    (Champion::Sona as u16, Champion::Sona.to_str()),
    (Champion::Soraka as u16, Champion::Soraka.to_str()),
    (Champion::Swain as u16, Champion::Swain.to_str()),
    (Champion::Sylas as u16, Champion::Sylas.to_str()),
    (Champion::Syndra as u16, Champion::Syndra.to_str()),
    (Champion::TahmKench as u16, Champion::TahmKench.to_str()),
    (Champion::Taliyah as u16, Champion::Taliyah.to_str()),
    (Champion::Talon as u16, Champion::Talon.to_str()),
    (Champion::Taric as u16, Champion::Taric.to_str()),
    (Champion::Teemo as u16, Champion::Teemo.to_str()),
    (Champion::Thresh as u16, Champion::Thresh.to_str()),
    (Champion::Tristana as u16, Champion::Tristana.to_str()),
    (Champion::Trundle as u16, Champion::Trundle.to_str()),
    (Champion::Tryndamere as u16, Champion::Tryndamere.to_str()),
    (Champion::TwistedFate as u16, Champion::TwistedFate.to_str()),
    (Champion::Twitch as u16, Champion::Twitch.to_str()),
    (Champion::Udyr as u16, Champion::Udyr.to_str()),
    (Champion::Urgot as u16, Champion::Urgot.to_str()),
    (Champion::Varus as u16, Champion::Varus.to_str()),
    (Champion::Vayne as u16, Champion::Vayne.to_str()),
    (Champion::Veigar as u16, Champion::Veigar.to_str()),
    (Champion::VelKoz as u16, Champion::VelKoz.to_str()),
    (Champion::Vex as u16, Champion::Vex.to_str()),
    (Champion::Vi as u16, Champion::Vi.to_str()),
    (Champion::Viego as u16, Champion::Viego.to_str()),
    (Champion::Viktor as u16, Champion::Viktor.to_str()),
    (Champion::Vladimir as u16, Champion::Vladimir.to_str()),
    (Champion::Volibear as u16, Champion::Volibear.to_str()),
    (Champion::Warwick as u16, Champion::Warwick.to_str()),
    (Champion::Wukong as u16, Champion::Wukong.to_str()),
    (Champion::Xayah as u16, Champion::Xayah.to_str()),
    (Champion::Xerath as u16, Champion::Xerath.to_str()),
    (Champion::XinZhao as u16, Champion::XinZhao.to_str()),
    (Champion::Yasuo as u16, Champion::Yasuo.to_str()),
    (Champion::Yone as u16, Champion::Yone.to_str()),
    (Champion::Yorick as u16, Champion::Yorick.to_str()),
    (Champion::Yuumi as u16, Champion::Yuumi.to_str()),
    (Champion::Zac as u16, Champion::Zac.to_str()),
    (Champion::Zed as u16, Champion::Zed.to_str()),
    (Champion::Zeri as u16, Champion::Zeri.to_str()),
    (Champion::Ziggs as u16, Champion::Ziggs.to_str()),
    (Champion::Zilean as u16, Champion::Zilean.to_str()),
    (Champion::Zoe as u16, Champion::Zoe.to_str()),
    (Champion::Zyra as u16, Champion::Zyra.to_str()),
];