[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
riven={workspace = true, optional = true}
serde={workspace = true}
bitcode = {workspace = true}
strum = {workspace = true}
num_enum = {workspace = true}
once_cell = "1.21.3"
[features]
ssr=["dep:riven"]