use bitcode::{Decode, Encode};
use num_enum::{IntoPrimitive, TryFromPrimitive};
use once_cell::sync::Lazy;
use strum::{EnumIter, IntoEnumIterator, IntoStaticStr};

#[repr(u16)]
#[derive(
    Debug, Clone, Copy, Eq, PartialEq, Hash, Encode, Decode,
    IntoPrimitive, TryFromPrimitive, EnumIter, IntoStaticStr
)]
#[derive(Default)]
pub enum Champion {
    #[strum(serialize = "UNKNOWN")]
    #[default]
    UNKNOWN = 0,

    #[strum(serialize = "Aatrox")]         Aatrox = 266,
    #[strum(serialize = "Ahri")]           Ahri = 103,
    #[strum(serialize = "Akali")]          Akali = 84,
    #[strum(serialize = "Akshan")]         Akshan = 166,
    #[strum(serialize = "Alistar")]        Alistar = 12,
    #[strum(serialize = "Ambessa")]        Ambessa = 799,
    #[strum(serialize = "Amumu")]          Amumu = 32,
    #[strum(serialize = "Anivia")]         Anivia = 34,
    #[strum(serialize = "Annie")]          Annie = 1,
    #[strum(serialize = "Aphelios")]       Aphelios = 523,
    #[strum(serialize = "Ashe")]           Ashe = 22,
    #[strum(serialize = "AurelionSol")]    AurelionSol = 136,
    #[strum(serialize = "Aurora")]         Aurora = 893,
    #[strum(serialize = "Azir")]           Azir = 268,
    #[strum(serialize = "Bard")]           Bard = 432,
    #[strum(serialize = "BelVeth")]        BelVeth = 200,
    #[strum(serialize = "Blitzcrank")]     Blitzcrank = 53,
    #[strum(serialize = "Brand")]          Brand = 63,
    #[strum(serialize = "Braum")]          Braum = 201,
    #[strum(serialize = "Briar")]          Briar = 233,
    #[strum(serialize = "Caitlyn")]        Caitlyn = 51,
    #[strum(serialize = "Camille")]        Camille = 164,
    #[strum(serialize = "Cassiopeia")]     Cassiopeia = 69,
    #[strum(serialize = "ChoGath")]        ChoGath = 31,
    #[strum(serialize = "Corki")]          Corki = 42,
    #[strum(serialize = "Darius")]         Darius = 122,
    #[strum(serialize = "Diana")]          Diana = 131,
    #[strum(serialize = "DrMundo")]        DrMundo = 36,
    #[strum(serialize = "Draven")]         Draven = 119,
    #[strum(serialize = "Ekko")]           Ekko = 245,
    #[strum(serialize = "Elise")]          Elise = 60,
    #[strum(serialize = "Evelynn")]        Evelynn = 28,
    #[strum(serialize = "Ezreal")]         Ezreal = 81,
    #[strum(serialize = "Fiddlesticks")]   Fiddlesticks = 9,
    #[strum(serialize = "Fiora")]          Fiora = 114,
    #[strum(serialize = "Fizz")]           Fizz = 105,
    #[strum(serialize = "Galio")]          Galio = 3,
    #[strum(serialize = "Gangplank")]      Gangplank = 41,
    #[strum(serialize = "Garen")]          Garen = 86,
    #[strum(serialize = "Gnar")]           Gnar = 150,
    #[strum(serialize = "Gragas")]         Gragas = 79,
    #[strum(serialize = "Graves")]         Graves = 104,
    #[strum(serialize = "Gwen")]           Gwen = 887,
    #[strum(serialize = "Hecarim")]        Hecarim = 120,
    #[strum(serialize = "Heimerdinger")]   Heimerdinger = 74,
    #[strum(serialize = "Hwei")]           Hwei = 910,
    #[strum(serialize = "Illaoi")]         Illaoi = 420,
    #[strum(serialize = "Irelia")]         Irelia = 39,
    #[strum(serialize = "Ivern")]          Ivern = 427,
    #[strum(serialize = "Janna")]          Janna = 40,
    #[strum(serialize = "JarvanIV")]       JarvanIV = 59,
    #[strum(serialize = "Jax")]            Jax = 24,
    #[strum(serialize = "Jayce")]          Jayce = 126,
    #[strum(serialize = "Jhin")]           Jhin = 202,
    #[strum(serialize = "Jinx")]           Jinx = 222,
    #[strum(serialize = "KSante")]         KSante = 897,
    #[strum(serialize = "KaiSa")]          KaiSa = 145,
    #[strum(serialize = "Kalista")]        Kalista = 429,
    #[strum(serialize = "Karma")]          Karma = 43,
    #[strum(serialize = "Karthus")]        Karthus = 30,
    #[strum(serialize = "Kassadin")]       Kassadin = 38,
    #[strum(serialize = "Katarina")]       Katarina = 55,
    #[strum(serialize = "Kayle")]          Kayle = 10,
    #[strum(serialize = "Kayn")]           Kayn = 141,
    #[strum(serialize = "Kennen")]         Kennen = 85,
    #[strum(serialize = "KhaZix")]         KhaZix = 121,
    #[strum(serialize = "Kindred")]        Kindred = 203,
    #[strum(serialize = "Kled")]           Kled = 240,
    #[strum(serialize = "KogMaw")]         KogMaw = 96,
    #[strum(serialize = "LeBlanc")]        LeBlanc = 7,
    #[strum(serialize = "LeeSin")]         LeeSin = 64,
    #[strum(serialize = "Leona")]          Leona = 89,
    #[strum(serialize = "Lillia")]         Lillia = 876,
    #[strum(serialize = "Lissandra")]      Lissandra = 127,
    #[strum(serialize = "Lucian")]         Lucian = 236,
    #[strum(serialize = "Lulu")]           Lulu = 117,
    #[strum(serialize = "Lux")]            Lux = 99,
    #[strum(serialize = "Malphite")]       Malphite = 54,
    #[strum(serialize = "Malzahar")]       Malzahar = 90,
    #[strum(serialize = "Maokai")]         Maokai = 57,
    #[strum(serialize = "MasterYi")]       MasterYi = 11,
    #[strum(serialize = "Mel")]            Mel = 800,
    #[strum(serialize = "Milio")]          Milio = 902,
    #[strum(serialize = "MissFortune")]    MissFortune = 21,
    #[strum(serialize = "Mordekaiser")]    Mordekaiser = 82,
    #[strum(serialize = "Morgana")]        Morgana = 25,
    #[strum(serialize = "Naafiri")]        Naafiri = 950,
    #[strum(serialize = "Nami")]           Nami = 267,
    #[strum(serialize = "Nasus")]          Nasus = 75,
    #[strum(serialize = "Nautilus")]       Nautilus = 111,
    #[strum(serialize = "Neeko")]          Neeko = 518,
    #[strum(serialize = "Nidalee")]        Nidalee = 76,
    #[strum(serialize = "Nilah")]          Nilah = 895,
    #[strum(serialize = "Nocturne")]       Nocturne = 56,
    #[strum(serialize = "NunuWillump")]    NunuWillump = 20,
    #[strum(serialize = "Olaf")]           Olaf = 2,
    #[strum(serialize = "Orianna")]        Orianna = 61,
    #[strum(serialize = "Ornn")]           Ornn = 516,
    #[strum(serialize = "Pantheon")]       Pantheon = 80,
    #[strum(serialize = "Poppy")]          Poppy = 78,
    #[strum(serialize = "Pyke")]           Pyke = 555,
    #[strum(serialize = "Qiyana")]         Qiyana = 246,
    #[strum(serialize = "Quinn")]          Quinn = 133,
    #[strum(serialize = "Rakan")]          Rakan = 497,
    #[strum(serialize = "Rammus")]         Rammus = 33,
    #[strum(serialize = "RekSai")]         RekSai = 421,
    #[strum(serialize = "Rell")]           Rell = 526,
    #[strum(serialize = "RenataGlasc")]    RenataGlasc = 888,
    #[strum(serialize = "Renekton")]       Renekton = 58,
    #[strum(serialize = "Rengar")]         Rengar = 107,
    #[strum(serialize = "Riven")]          Riven = 92,
    #[strum(serialize = "Rumble")]         Rumble = 68,
    #[strum(serialize = "Ryze")]           Ryze = 13,
    #[strum(serialize = "Samira")]         Samira = 360,
    #[strum(serialize = "Sejuani")]        Sejuani = 113,
    #[strum(serialize = "Senna")]          Senna = 235,
    #[strum(serialize = "Seraphine")]      Seraphine = 147,
    #[strum(serialize = "Sett")]           Sett = 875,
    #[strum(serialize = "Shaco")]          Shaco = 35,
    #[strum(serialize = "Shen")]           Shen = 98,
    #[strum(serialize = "Shyvana")]        Shyvana = 102,
    #[strum(serialize = "Singed")]         Singed = 27,
    #[strum(serialize = "Sion")]           Sion = 14,
    #[strum(serialize = "Sivir")]          Sivir = 15,
    #[strum(serialize = "Skarner")]        Skarner = 72,
    #[strum(serialize = "Smolder")]        Smolder = 901,
    #[strum(serialize = "Sona")]           Sona = 37,
    #[strum(serialize = "Soraka")]         Soraka = 16,
    #[strum(serialize = "Swain")]          Swain = 50,
    #[strum(serialize = "Sylas")]          Sylas = 517,
    #[strum(serialize = "Syndra")]         Syndra = 134,
    #[strum(serialize = "TahmKench")]      TahmKench = 223,
    #[strum(serialize = "Taliyah")]        Taliyah = 163,
    #[strum(serialize = "Talon")]          Talon = 91,
    #[strum(serialize = "Taric")]          Taric = 44,
    #[strum(serialize = "Teemo")]          Teemo = 17,
    #[strum(serialize = "Thresh")]         Thresh = 412,
    #[strum(serialize = "Tristana")]       Tristana = 18,
    #[strum(serialize = "Trundle")]        Trundle = 48,
    #[strum(serialize = "Tryndamere")]     Tryndamere = 23,
    #[strum(serialize = "TwistedFate")]    TwistedFate = 4,
    #[strum(serialize = "Twitch")]         Twitch = 29,
    #[strum(serialize = "Udyr")]           Udyr = 77,
    #[strum(serialize = "Urgot")]          Urgot = 6,
    #[strum(serialize = "Varus")]          Varus = 110,
    #[strum(serialize = "Vayne")]          Vayne = 67,
    #[strum(serialize = "Veigar")]         Veigar = 45,
    #[strum(serialize = "VelKoz")]         VelKoz = 161,
    #[strum(serialize = "Vex")]            Vex = 711,
    #[strum(serialize = "Vi")]             Vi = 254,
    #[strum(serialize = "Viego")]          Viego = 234,
    #[strum(serialize = "Viktor")]         Viktor = 112,
    #[strum(serialize = "Vladimir")]       Vladimir = 8,
    #[strum(serialize = "Volibear")]       Volibear = 106,
    #[strum(serialize = "Warwick")]        Warwick = 19,
    #[strum(serialize = "Wukong")]         Wukong = 62,
    #[strum(serialize = "Xayah")]          Xayah = 498,
    #[strum(serialize = "Xerath")]         Xerath = 101,
    #[strum(serialize = "XinZhao")]        XinZhao = 5,
    #[strum(serialize = "Yasuo")]          Yasuo = 157,
    #[strum(serialize = "Yone")]           Yone = 777,
    #[strum(serialize = "Yorick")]         Yorick = 83,
    #[strum(serialize = "Yunara")]         Yunara = 804,
    #[strum(serialize = "Yuumi")]          Yuumi = 350,
    #[strum(serialize = "Zac")]            Zac = 154,
    #[strum(serialize = "Zed")]            Zed = 238,
    #[strum(serialize = "Zeri")]           Zeri = 221,
    #[strum(serialize = "Ziggs")]          Ziggs = 115,
    #[strum(serialize = "Zilean")]         Zilean = 26,
    #[strum(serialize = "Zoe")]            Zoe = 142,
    #[strum(serialize = "Zyra")]           Zyra = 143,
}


impl Champion {
    #[inline]
    pub fn id(self) -> u16 { self.into() }

    #[inline]
    pub fn label(self) -> &'static str { self.into() }

    #[inline]
    pub fn options_all() -> Vec<(u16, &'static str)> {
        Champion::iter().filter(|c|c.id() != 0).map(|c| (c.id(), c.label())).collect()
    }
}

// Keep a drop-in replacement for CHAMPION_OPTIONS (now lazy).
pub static CHAMPION_OPTIONS: Lazy<Vec<(u16, &'static str)>> = Lazy::new(Champion::options_all);
