use bitcode::{Decode, Encode};

#[repr(u8)]
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, Encode, Decode)]
pub enum Queue {
    Custom,
    SummonersRift5v5BlindPickDeprecated2,
    SummonersRift5v5RankedSoloDeprecated4,
    SummonersRift5v5RankedPremade,
    SummonersRiftCoOpVsAi,
    TwistedTreeline3v3Normal,
    TwistedTreeline3v3RankedFlexDeprecated9,
    SummonersRift5v5DraftPickDeprecated14,
    CrystalScar5v5DominionBlindPick,
    CrystalScar5v5DominionDraftPick,
    CrystalScarDominionCoOpVsAi,
    SummonersRiftCoOpVsAiIntroBotDeprecated31,
    SummonersRiftCoOpVsAiBeginnerBotDeprecated32,
    SummonersRiftCoOpVsAiIntermediateBotDeprecated33,
    TwistedTreeline3v3RankedTeam,
    SummonersRift5v5RankedTeam,
    TwistedTreelineCoOpVsAi,
    SummonersRift5v5TeamBuilder,
    HowlingAbyss5v5AramDeprecated65,
    HowlingAbyssAramCoOpVsAi,
    SummonersRiftOneForAllDeprecated70,
    HowlingAbyss1v1SnowdownShowdown,
    HowlingAbyss2v2SnowdownShowdown,
    SummonersRift6v6Hexakill,
    SummonersRiftUltraRapidFire,
    HowlingAbyssOneForAllMirrorMode,
    SummonersRiftCoOpVsAiUltraRapidFire,
    SummonersRiftDoomBotsRank1,
    SummonersRiftDoomBotsRank2,
    SummonersRiftDoomBotsRank5,
    CrystalScarAscensionDeprecated96,
    TwistedTreeline6v6Hexakill,
    ButchersBridge5v5Aram,
    HowlingAbyssLegendOfThePoroKingDeprecated300,
    SummonersRiftNemesis,
    SummonersRiftBlackMarketBrawlers,
    SummonersRiftNexusSiegeDeprecated315,
    CrystalScarDefinitelyNotDominion,
    SummonersRiftArurfDeprecated318,
    SummonersRiftAllRandom,
    SummonersRift5v5DraftPick,
    SummonersRift5v5RankedDynamic,
    SummonersRift5v5RankedSolo,
    SummonersRift5v5BlindPick,
    SummonersRift5v5RankedFlex,
    HowlingAbyss5v5Aram,
    TwistedTreeline3v3BlindPick,
    TwistedTreeline3v3RankedFlexDeprecated470,
    SummonersRiftNormalQuickplay,
    SummonersRiftBloodHuntAssassin,
    CosmicRuinsDarkStarSingularity,
    SummonersRiftClash,
    HowlingAbyssAramClash,
    TwistedTreelineCoOpVsAiIntermediateBot,
    TwistedTreelineCoOpVsAiIntroBot,
    TwistedTreelineCoOpVsAiBeginnerBot,
    SummonersRiftCoOpVsAiIntroBot,
    SummonersRiftCoOpVsAiBeginnerBot,
    SummonersRiftCoOpVsAiIntermediateBot,
    SummonersRiftArurf,
    CrystalScarAscension,
    HowlingAbyssLegendOfThePoroKing,
    SummonersRiftNexusSiege,
    SummonersRiftDoomBotsVoting,
    SummonersRiftDoomBotsStandard,
    ValoranCityParkStarGuardianInvasionNormal,
    ValoranCityParkStarGuardianInvasionOnslaught,
    OverchargeProjectHunters,
    SummonersRiftSnowArurf,
    SummonersRiftOneForAll,
    CrashSiteOdysseyExtractionIntro,
    CrashSiteOdysseyExtractionCadet,
    CrashSiteOdysseyExtractionCrewmember,
    CrashSiteOdysseyExtractionCaptain,
    CrashSiteOdysseyExtractionOnslaught,
    ConvergenceTeamfightTactics,
    ConvergenceTeamfightTactics1v0,
    ConvergenceTeamfightTactics2v0,
    ConvergenceRankedTeamfightTactics,
    ConvergenceTeamfightTacticsTutorial,
    ConvergenceTeamfightTacticsSimulation,
    ConvergenceRankedTeamfightTacticsHyperRoll,
    ConvergenceRankedTeamfightTacticsDoubleUpWorkshopDeprecated1150,
    ConvergenceRankedTeamfightTacticsDoubleUpWorkshop,
    NexusBlitzDeprecated1200,
    ConvergenceTeamfightTacticsChonccsTreasure,
    NexusBlitz,
    SummonersRiftUltimateSpellbook,
    Arena2v2v2v2Cherry,
    RingsOfWrathArenaCherryGames,
    SwarmSoloStrawberryGames,
    SwarmDuoStrawberryGames,
    SwarmTrioStrawberryGames,
    SwarmQuadStrawberryGames,
    SummonersRiftPickUrf,
    SummonersRiftTutorial1,
    SummonersRiftTutorial2,
    SummonersRiftTutorial3,
    ConvergenceTeamfightTacticsSet35Revival,
}

impl Queue {
    pub const fn to_str(&self) -> &'static str {
        match self {
            Queue::SummonersRift5v5DraftPick => "Normal Draft Pick",
            Queue::SummonersRift5v5BlindPick => "Normal Blind Pick",
            Queue::SummonersRift5v5RankedSolo => "Ranked Solo/Duo",
            Queue::SummonersRift5v5RankedFlex => "Ranked Flex",
            Queue::HowlingAbyss5v5Aram => "ARAM",
            Queue::SummonersRiftArurf => "ARURF",
            Queue::SummonersRiftOneForAll => "One for All",
            Queue::Arena2v2v2v2Cherry => "2v2v2v2 Cherry",
            Queue::SummonersRiftPickUrf => "Pick URF",
            Queue::SummonersRiftUltimateSpellbook => "Ultimate Spellbook",
            Queue::SummonersRiftNexusSiege => "Nexus Siege",
            Queue::SummonersRiftClash => "Clash",
            Queue::SummonersRiftNormalQuickplay => "Normal Quickplay",
            Queue::NexusBlitz => "Nexus Blitz",
            _ => "Unknown",
        }
    }

    pub fn to_u16(&self) -> u16 {
        match self {
            Queue::Custom => 0,
            Queue::SummonersRift5v5BlindPickDeprecated2 => 2,
            Queue::SummonersRift5v5RankedSoloDeprecated4 => 4,
            Queue::SummonersRift5v5RankedPremade => 6,
            Queue::SummonersRiftCoOpVsAi => 7,
            Queue::TwistedTreeline3v3Normal => 8,
            Queue::TwistedTreeline3v3RankedFlexDeprecated9 => 9,
            Queue::SummonersRift5v5DraftPickDeprecated14 => 14,
            Queue::CrystalScar5v5DominionBlindPick => 16,
            Queue::CrystalScar5v5DominionDraftPick => 17,
            Queue::CrystalScarDominionCoOpVsAi => 25,
            Queue::SummonersRiftCoOpVsAiIntroBotDeprecated31 => 31,
            Queue::SummonersRiftCoOpVsAiBeginnerBotDeprecated32 => 32,
            Queue::SummonersRiftCoOpVsAiIntermediateBotDeprecated33 => 33,
            Queue::TwistedTreeline3v3RankedTeam => 41,
            Queue::SummonersRift5v5RankedTeam => 42,
            Queue::TwistedTreelineCoOpVsAi => 52,
            Queue::SummonersRift5v5TeamBuilder => 61,
            Queue::HowlingAbyss5v5AramDeprecated65 => 65,
            Queue::HowlingAbyssAramCoOpVsAi => 67,
            Queue::SummonersRiftOneForAllDeprecated70 => 70,
            Queue::HowlingAbyss1v1SnowdownShowdown => 72,
            Queue::HowlingAbyss2v2SnowdownShowdown => 73,
            Queue::SummonersRift6v6Hexakill => 75,
            Queue::SummonersRiftUltraRapidFire => 76,
            Queue::HowlingAbyssOneForAllMirrorMode => 78,
            Queue::SummonersRiftCoOpVsAiUltraRapidFire => 83,
            Queue::SummonersRiftDoomBotsRank1 => 91,
            Queue::SummonersRiftDoomBotsRank2 => 92,
            Queue::SummonersRiftDoomBotsRank5 => 93,
            Queue::CrystalScarAscensionDeprecated96 => 96,
            Queue::TwistedTreeline6v6Hexakill => 98,
            Queue::ButchersBridge5v5Aram => 100,
            Queue::HowlingAbyssLegendOfThePoroKingDeprecated300 => 300,
            Queue::SummonersRiftNemesis => 310,
            Queue::SummonersRiftBlackMarketBrawlers => 313,
            Queue::SummonersRiftNexusSiegeDeprecated315 => 315,
            Queue::CrystalScarDefinitelyNotDominion => 317,
            Queue::SummonersRiftArurfDeprecated318 => 318,
            Queue::SummonersRiftAllRandom => 325,
            Queue::SummonersRift5v5DraftPick => 400,
            Queue::SummonersRift5v5RankedDynamic => 410,
            Queue::SummonersRift5v5RankedSolo => 420,
            Queue::SummonersRift5v5BlindPick => 430,
            Queue::SummonersRift5v5RankedFlex => 440,
            Queue::HowlingAbyss5v5Aram => 450,
            Queue::TwistedTreeline3v3BlindPick => 460,
            Queue::TwistedTreeline3v3RankedFlexDeprecated470 => 470,
            Queue::SummonersRiftNormalQuickplay => 490,
            Queue::SummonersRiftBloodHuntAssassin => 600,
            Queue::CosmicRuinsDarkStarSingularity => 610,
            Queue::SummonersRiftClash => 700,
            Queue::HowlingAbyssAramClash => 720,
            Queue::TwistedTreelineCoOpVsAiIntermediateBot => 800,
            Queue::TwistedTreelineCoOpVsAiIntroBot => 810,
            Queue::TwistedTreelineCoOpVsAiBeginnerBot => 820,
            Queue::SummonersRiftCoOpVsAiIntroBot => 830,
            Queue::SummonersRiftCoOpVsAiBeginnerBot => 840,
            Queue::SummonersRiftCoOpVsAiIntermediateBot => 850,
            Queue::SummonersRiftArurf => 900,
            Queue::CrystalScarAscension => 910,
            Queue::HowlingAbyssLegendOfThePoroKing => 920,
            Queue::SummonersRiftNexusSiege => 940,
            Queue::SummonersRiftDoomBotsVoting => 950,
            Queue::SummonersRiftDoomBotsStandard => 960,
            Queue::ValoranCityParkStarGuardianInvasionNormal => 980,
            Queue::ValoranCityParkStarGuardianInvasionOnslaught => 990,
            Queue::OverchargeProjectHunters => 1000,
            Queue::SummonersRiftSnowArurf => 1010,
            Queue::SummonersRiftOneForAll => 1020,
            Queue::CrashSiteOdysseyExtractionIntro => 1030,
            Queue::CrashSiteOdysseyExtractionCadet => 1040,
            Queue::CrashSiteOdysseyExtractionCrewmember => 1050,
            Queue::CrashSiteOdysseyExtractionCaptain => 1060,
            Queue::CrashSiteOdysseyExtractionOnslaught => 1070,
            Queue::ConvergenceTeamfightTactics => 1090,
            Queue::ConvergenceTeamfightTactics1v0 => 1091,
            Queue::ConvergenceTeamfightTactics2v0 => 1092,
            Queue::ConvergenceRankedTeamfightTactics => 1100,
            Queue::ConvergenceTeamfightTacticsTutorial => 1110,
            Queue::ConvergenceTeamfightTacticsSimulation => 1111,
            Queue::ConvergenceRankedTeamfightTacticsHyperRoll => 1130,
            Queue::ConvergenceRankedTeamfightTacticsDoubleUpWorkshopDeprecated1150 => 1150,
            Queue::ConvergenceRankedTeamfightTacticsDoubleUpWorkshop => 1160,
            Queue::NexusBlitzDeprecated1200 => 1200,
            Queue::ConvergenceTeamfightTacticsChonccsTreasure => 1210,
            Queue::NexusBlitz => 1300,
            Queue::SummonersRiftUltimateSpellbook => 1400,
            Queue::Arena2v2v2v2Cherry => 1700,
            Queue::RingsOfWrathArenaCherryGames => 1710,
            Queue::SwarmSoloStrawberryGames => 1810,
            Queue::SwarmDuoStrawberryGames => 1820,
            Queue::SwarmTrioStrawberryGames => 1830,
            Queue::SwarmQuadStrawberryGames => 1840,
            Queue::SummonersRiftPickUrf => 1900,
            Queue::SummonersRiftTutorial1 => 2000,
            Queue::SummonersRiftTutorial2 => 2010,
            Queue::SummonersRiftTutorial3 => 2020,
            Queue::ConvergenceTeamfightTacticsSet35Revival => 6000,
        }
    }

    pub fn from_u16(value: u16) -> Self {
        match value {
            0 => Queue::Custom,
            2 => Queue::SummonersRift5v5BlindPickDeprecated2,
            4 => Queue::SummonersRift5v5RankedSoloDeprecated4,
            6 => Queue::SummonersRift5v5RankedPremade,
            7 => Queue::SummonersRiftCoOpVsAi,
            8 => Queue::TwistedTreeline3v3Normal,
            9 => Queue::TwistedTreeline3v3RankedFlexDeprecated9,
            14 => Queue::SummonersRift5v5DraftPickDeprecated14,
            16 => Queue::CrystalScar5v5DominionBlindPick,
            17 => Queue::CrystalScar5v5DominionDraftPick,
            25 => Queue::CrystalScarDominionCoOpVsAi,
            31 => Queue::SummonersRiftCoOpVsAiIntroBotDeprecated31,
            32 => Queue::SummonersRiftCoOpVsAiBeginnerBotDeprecated32,
            33 => Queue::SummonersRiftCoOpVsAiIntermediateBotDeprecated33,
            41 => Queue::TwistedTreeline3v3RankedTeam,
            42 => Queue::SummonersRift5v5RankedTeam,
            52 => Queue::TwistedTreelineCoOpVsAi,
            61 => Queue::SummonersRift5v5TeamBuilder,
            65 => Queue::HowlingAbyss5v5AramDeprecated65,
            67 => Queue::HowlingAbyssAramCoOpVsAi,
            70 => Queue::SummonersRiftOneForAllDeprecated70,
            72 => Queue::HowlingAbyss1v1SnowdownShowdown,
            73 => Queue::HowlingAbyss2v2SnowdownShowdown,
            75 => Queue::SummonersRift6v6Hexakill,
            76 => Queue::SummonersRiftUltraRapidFire,
            78 => Queue::HowlingAbyssOneForAllMirrorMode,
            83 => Queue::SummonersRiftCoOpVsAiUltraRapidFire,
            91 => Queue::SummonersRiftDoomBotsRank1,
            92 => Queue::SummonersRiftDoomBotsRank2,
            93 => Queue::SummonersRiftDoomBotsRank5,
            96 => Queue::CrystalScarAscensionDeprecated96,
            98 => Queue::TwistedTreeline6v6Hexakill,
            100 => Queue::ButchersBridge5v5Aram,
            300 => Queue::HowlingAbyssLegendOfThePoroKingDeprecated300,
            310 => Queue::SummonersRiftNemesis,
            313 => Queue::SummonersRiftBlackMarketBrawlers,
            315 => Queue::SummonersRiftNexusSiegeDeprecated315,
            317 => Queue::CrystalScarDefinitelyNotDominion,
            318 => Queue::SummonersRiftArurfDeprecated318,
            325 => Queue::SummonersRiftAllRandom,
            400 => Queue::SummonersRift5v5DraftPick,
            410 => Queue::SummonersRift5v5RankedDynamic,
            420 => Queue::SummonersRift5v5RankedSolo,
            430 => Queue::SummonersRift5v5BlindPick,
            440 => Queue::SummonersRift5v5RankedFlex,
            450 => Queue::HowlingAbyss5v5Aram,
            460 => Queue::TwistedTreeline3v3BlindPick,
            470 => Queue::TwistedTreeline3v3RankedFlexDeprecated470,
            490 => Queue::SummonersRiftNormalQuickplay,
            600 => Queue::SummonersRiftBloodHuntAssassin,
            610 => Queue::CosmicRuinsDarkStarSingularity,
            700 => Queue::SummonersRiftClash,
            720 => Queue::HowlingAbyssAramClash,
            800 => Queue::TwistedTreelineCoOpVsAiIntermediateBot,
            810 => Queue::TwistedTreelineCoOpVsAiIntroBot,
            820 => Queue::TwistedTreelineCoOpVsAiBeginnerBot,
            830 => Queue::SummonersRiftCoOpVsAiIntroBot,
            840 => Queue::SummonersRiftCoOpVsAiBeginnerBot,
            850 => Queue::SummonersRiftCoOpVsAiIntermediateBot,
            900 => Queue::SummonersRiftArurf,
            910 => Queue::CrystalScarAscension,
            920 => Queue::HowlingAbyssLegendOfThePoroKing,
            940 => Queue::SummonersRiftNexusSiege,
            950 => Queue::SummonersRiftDoomBotsVoting,
            960 => Queue::SummonersRiftDoomBotsStandard,
            980 => Queue::ValoranCityParkStarGuardianInvasionNormal,
            990 => Queue::ValoranCityParkStarGuardianInvasionOnslaught,
            1000 => Queue::OverchargeProjectHunters,
            1010 => Queue::SummonersRiftSnowArurf,
            1020 => Queue::SummonersRiftOneForAll,
            1030 => Queue::CrashSiteOdysseyExtractionIntro,
            1040 => Queue::CrashSiteOdysseyExtractionCadet,
            1050 => Queue::CrashSiteOdysseyExtractionCrewmember,
            1060 => Queue::CrashSiteOdysseyExtractionCaptain,
            1070 => Queue::CrashSiteOdysseyExtractionOnslaught,
            1090 => Queue::ConvergenceTeamfightTactics,
            1091 => Queue::ConvergenceTeamfightTactics1v0,
            1092 => Queue::ConvergenceTeamfightTactics2v0,
            1100 => Queue::ConvergenceRankedTeamfightTactics,
            1110 => Queue::ConvergenceTeamfightTacticsTutorial,
            1111 => Queue::ConvergenceTeamfightTacticsSimulation,
            1130 => Queue::ConvergenceRankedTeamfightTacticsHyperRoll,
            1150 => Queue::ConvergenceRankedTeamfightTacticsDoubleUpWorkshopDeprecated1150,
            1160 => Queue::ConvergenceRankedTeamfightTacticsDoubleUpWorkshop,
            1200 => Queue::NexusBlitzDeprecated1200,
            1210 => Queue::ConvergenceTeamfightTacticsChonccsTreasure,
            1300 => Queue::NexusBlitz,
            1400 => Queue::SummonersRiftUltimateSpellbook,
            1700 => Queue::Arena2v2v2v2Cherry,
            1710 => Queue::RingsOfWrathArenaCherryGames,
            1810 => Queue::SwarmSoloStrawberryGames,
            1820 => Queue::SwarmDuoStrawberryGames,
            1830 => Queue::SwarmTrioStrawberryGames,
            1840 => Queue::SwarmQuadStrawberryGames,
            1900 => Queue::SummonersRiftPickUrf,
            2000 => Queue::SummonersRiftTutorial1,
            2010 => Queue::SummonersRiftTutorial2,
            2020 => Queue::SummonersRiftTutorial3,
            6000 => Queue::ConvergenceTeamfightTacticsSet35Revival,
            _ => Queue::Custom,
        }
    }
}

pub static QUEUE_OPTIONS: &[(u8, &str)] = &[
    (
        Queue::SummonersRift5v5DraftPick as u8,
        Queue::SummonersRift5v5DraftPick.to_str(),
    ),
    (
        Queue::SummonersRift5v5BlindPick as u8,
        Queue::SummonersRift5v5BlindPick.to_str(),
    ),
    (
        Queue::SummonersRift5v5RankedSolo as u8,
        Queue::SummonersRift5v5RankedSolo.to_str(),
    ),
    (
        Queue::SummonersRift5v5RankedFlex as u8,
        Queue::SummonersRift5v5RankedFlex.to_str(),
    ),
    (
        Queue::HowlingAbyss5v5Aram as u8,
        Queue::HowlingAbyss5v5Aram.to_str(),
    ),
    (
        Queue::SummonersRiftArurf as u8,
        Queue::SummonersRiftArurf.to_str(),
    ),
    (
        Queue::SummonersRiftOneForAll as u8,
        Queue::SummonersRiftOneForAll.to_str(),
    ),
    (
        Queue::Arena2v2v2v2Cherry as u8,
        Queue::Arena2v2v2v2Cherry.to_str(),
    ),
    (
        Queue::SummonersRiftPickUrf as u8,
        Queue::SummonersRiftPickUrf.to_str(),
    ),
    (
        Queue::SummonersRiftUltimateSpellbook as u8,
        Queue::SummonersRiftUltimateSpellbook.to_str(),
    ),
    (
        Queue::SummonersRiftNexusSiege as u8,
        Queue::SummonersRiftNexusSiege.to_str(),
    ),
    (
        Queue::SummonersRiftClash as u8,
        Queue::SummonersRiftClash.to_str(),
    ),
    (
        Queue::SummonersRiftNormalQuickplay as u8,
        Queue::SummonersRiftNormalQuickplay.to_str(),
    ),
    (Queue::NexusBlitz as u8, Queue::NexusBlitz.to_str()),
];

impl From<u8> for Queue {
    fn from(value: u8) -> Self {
        match value {
            0 => Queue::Custom,
            1 => Queue::SummonersRift5v5BlindPickDeprecated2,
            2 => Queue::SummonersRift5v5RankedSoloDeprecated4,
            3 => Queue::SummonersRift5v5RankedPremade,
            4 => Queue::SummonersRiftCoOpVsAi,
            5 => Queue::TwistedTreeline3v3Normal,
            6 => Queue::TwistedTreeline3v3RankedFlexDeprecated9,
            7 => Queue::SummonersRift5v5DraftPickDeprecated14,
            8 => Queue::CrystalScar5v5DominionBlindPick,
            9 => Queue::CrystalScar5v5DominionDraftPick,
            10 => Queue::CrystalScarDominionCoOpVsAi,
            11 => Queue::SummonersRiftCoOpVsAiIntroBotDeprecated31,
            12 => Queue::SummonersRiftCoOpVsAiBeginnerBotDeprecated32,
            13 => Queue::SummonersRiftCoOpVsAiIntermediateBotDeprecated33,
            14 => Queue::TwistedTreeline3v3RankedTeam,
            15 => Queue::SummonersRift5v5RankedTeam,
            16 => Queue::TwistedTreelineCoOpVsAi,
            17 => Queue::SummonersRift5v5TeamBuilder,
            18 => Queue::HowlingAbyss5v5AramDeprecated65,
            19 => Queue::HowlingAbyssAramCoOpVsAi,
            20 => Queue::SummonersRiftOneForAllDeprecated70,
            21 => Queue::HowlingAbyss1v1SnowdownShowdown,
            22 => Queue::HowlingAbyss2v2SnowdownShowdown,
            23 => Queue::SummonersRift6v6Hexakill,
            24 => Queue::SummonersRiftUltraRapidFire,
            25 => Queue::HowlingAbyssOneForAllMirrorMode,
            26 => Queue::SummonersRiftCoOpVsAiUltraRapidFire,
            27 => Queue::SummonersRiftDoomBotsRank1,
            28 => Queue::SummonersRiftDoomBotsRank2,
            29 => Queue::SummonersRiftDoomBotsRank5,
            30 => Queue::CrystalScarAscensionDeprecated96,
            31 => Queue::TwistedTreeline6v6Hexakill,
            32 => Queue::ButchersBridge5v5Aram,
            33 => Queue::HowlingAbyssLegendOfThePoroKingDeprecated300,
            34 => Queue::SummonersRiftNemesis,
            35 => Queue::SummonersRiftBlackMarketBrawlers,
            36 => Queue::SummonersRiftNexusSiegeDeprecated315,
            37 => Queue::CrystalScarDefinitelyNotDominion,
            38 => Queue::SummonersRiftArurfDeprecated318,
            39 => Queue::SummonersRiftAllRandom,
            40 => Queue::SummonersRift5v5DraftPick,
            41 => Queue::SummonersRift5v5RankedDynamic,
            42 => Queue::SummonersRift5v5RankedSolo,
            43 => Queue::SummonersRift5v5BlindPick,
            44 => Queue::SummonersRift5v5RankedFlex,
            45 => Queue::HowlingAbyss5v5Aram,
            46 => Queue::TwistedTreeline3v3BlindPick,
            47 => Queue::TwistedTreeline3v3RankedFlexDeprecated470,
            48 => Queue::SummonersRiftNormalQuickplay,
            49 => Queue::SummonersRiftBloodHuntAssassin,
            50 => Queue::CosmicRuinsDarkStarSingularity,
            51 => Queue::SummonersRiftClash,
            52 => Queue::HowlingAbyssAramClash,
            53 => Queue::TwistedTreelineCoOpVsAiIntermediateBot,
            54 => Queue::TwistedTreelineCoOpVsAiIntroBot,
            55 => Queue::TwistedTreelineCoOpVsAiBeginnerBot,
            56 => Queue::SummonersRiftCoOpVsAiIntroBot,
            57 => Queue::SummonersRiftCoOpVsAiBeginnerBot,
            58 => Queue::SummonersRiftCoOpVsAiIntermediateBot,
            59 => Queue::SummonersRiftArurf,
            60 => Queue::CrystalScarAscension,
            61 => Queue::HowlingAbyssLegendOfThePoroKing,
            62 => Queue::SummonersRiftNexusSiege,
            63 => Queue::SummonersRiftDoomBotsVoting,
            64 => Queue::SummonersRiftDoomBotsStandard,
            65 => Queue::ValoranCityParkStarGuardianInvasionNormal,
            66 => Queue::ValoranCityParkStarGuardianInvasionOnslaught,
            67 => Queue::OverchargeProjectHunters,
            68 => Queue::SummonersRiftSnowArurf,
            69 => Queue::SummonersRiftOneForAll,
            70 => Queue::CrashSiteOdysseyExtractionIntro,
            71 => Queue::CrashSiteOdysseyExtractionCadet,
            72 => Queue::CrashSiteOdysseyExtractionCrewmember,
            73 => Queue::CrashSiteOdysseyExtractionCaptain,
            74 => Queue::CrashSiteOdysseyExtractionOnslaught,
            75 => Queue::ConvergenceTeamfightTactics,
            76 => Queue::ConvergenceTeamfightTactics1v0,
            77 => Queue::ConvergenceTeamfightTactics2v0,
            78 => Queue::ConvergenceRankedTeamfightTactics,
            79 => Queue::ConvergenceTeamfightTacticsTutorial,
            80 => Queue::ConvergenceTeamfightTacticsSimulation,
            81 => Queue::ConvergenceRankedTeamfightTacticsHyperRoll,
            82 => Queue::ConvergenceRankedTeamfightTacticsDoubleUpWorkshopDeprecated1150,
            83 => Queue::ConvergenceRankedTeamfightTacticsDoubleUpWorkshop,
            84 => Queue::NexusBlitzDeprecated1200,
            85 => Queue::ConvergenceTeamfightTacticsChonccsTreasure,
            86 => Queue::NexusBlitz,
            87 => Queue::SummonersRiftUltimateSpellbook,
            88 => Queue::Arena2v2v2v2Cherry,
            89 => Queue::RingsOfWrathArenaCherryGames,
            90 => Queue::SwarmSoloStrawberryGames,
            91 => Queue::SwarmDuoStrawberryGames,
            92 => Queue::SwarmTrioStrawberryGames,
            93 => Queue::SwarmQuadStrawberryGames,
            94 => Queue::SummonersRiftPickUrf,
            95 => Queue::SummonersRiftTutorial1,
            96 => Queue::SummonersRiftTutorial2,
            97 => Queue::SummonersRiftTutorial3,
            98 => Queue::ConvergenceTeamfightTacticsSet35Revival,
            _ => Queue::Custom,
        }
    }
}
